compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-tools/apollo-engine-loader": "*"
  "@inquirer/checkbox@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/confirm@5.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/core@10.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/editor@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/expand@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/input@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/number@3.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/password@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/rawlist@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/search@3.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/select@4.0.0":
    dependencies:
      "@types/node": "*"
  "@rushstack/eslint-patch@*":
    peerDependencies:
      "@eslint/eslintrc": "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/react-transition-group@4.4.10":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-next@*:
    peerDependencies:
      "@eslint/eslintrc": "*"
      next: "*"
      react: "*"
      react-dom: "*"
  next@*:
    dependencies:
      sharp: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.5.0.cjs
